---
title: Project 2
summary: An example of linking directly to an external project website using `external_link`.
date: "2016-04-27T00:00:00Z"

# Optional external URL for project (replaces project detail page).
external_link: http://example.org

